# This dictionary maps broader categories to a list of specific keywords/phrases
# that CLIP will use to calculate similarity scores.
# The order of categories here can imply a slight preference if scores are close,
# but the classification logic in image_analyzer.py handles primary categorization.
CATEGORIES = {
    "architecture": [
        "a building",
        "a house",
        "a skyscraper",
        "a bridge",
        "a monument",
        "an architectural structure",
        "an urban landscape",
        "a city skyline",
        "historical architecture",
        "modern architecture",
        "a temple",
        "a church",
        "a mosque",
        "a cathedral",
        "a pagoda",
        "a religious building",
        "a historical landmark",
        "an ancient ruin",
        "a palace",
        "a castle",
        "a traditional building",
        "a shrine",
    ],
    "people": [
        "a person",
        "a man",
        "a woman",
        "people",
        "a crowd",
        "a portrait",
        "a selfie",
        "human face",
        "a group of people",
        "a child",
        "an adult",
        "family",
        "friends",
        "strangers",
        "a person outdoors",
        "a person indoors",
        "a person with a pet",
        "a person wearing a hat",
        "a person with a mustache",
        "a person with facial hair",
        "multiple people",
        "three people",
        "two people",
        "four people",
        "people posing",
        "people smiling",
        "casual photo of people",
        "informal portrait",
        "group selfie",
        "people together",
        "social gathering",
        "people in a room",
        "people at home",
        # Added for cartoon/illustrated people to help with miscategorization
        "a cartoon person",
        "cartoon characters",
        "drawn people",
        "an illustration of people",
        "an animated character",
        "comic characters",
    ],
    "sightseeing": [
        "tourist attraction",
        "sightseeing",
        "a tourist spot",
        "landmark",
        "historic site",
        "a guided tour",
        "city sightseeing",
        "tourists",
        "view of city",
        "scenic view",
        "arch",
        "tower",
        "beach",
        "park",
        "bench",
        "building",
        "monument",
        "shrine",
    ],
    "documents": [
        "a document",
        "a paper",
        "a certificate",
        "a resume",
        "an invoice",
        "a receipt",
        "a contract",
        "a form",
        "a letter",
        "a handwritten note",
        "a report",
        "a financial statement",
        "a diagram",
        "a blueprint",
        "a schematic",
        "a drawing",
        "a map",
        "a legal document",
        "a formal paper",
        "a scanned document",
        "a printed page",
        "a text document",
        # Added for signs, posters, general text boards to help with 'sign' image
        "a sign",
        "a poster",
        "a notice",
        "a billboard",
        "a text board",
        "handwritten sign",
        "printed sign",
    ],
    "achievements": [
        "a trophy on display",
        "an award ceremony",
        "a medal presentation",
        "a championship trophy on a table",
        "a winner's medal being held",
        "a certificate of achievement hanging on wall",
        "a professional certification diploma in frame",
        "an industry recognition award on shelf",
        "a graduation cap and gown ceremony",
        "a diploma scroll in formal setting",
        "a success celebration with trophy",
        "a winning moment with award",
        "proof of accomplishment document",
        "a celebratory award presentation",
        "a recognition plaque mounted",
        "a commendation certificate displayed",
        "formal award ceremony",
        "trophy case display",
        "medal collection",
        "achievement wall display",
        "graduation ceremony photo",
    ],
    "objects": [
        "a common object",
        "a household item",
        "a tool",
        "a device",
        "furniture",
        "a piece of equipment",
        "a book",
        "a stack of books",
        "a bookshelf",
        "a novel",
        "a textbook",
        "reading material",
        "a mobile phone",
        "a laptop",
        "a camera",
        "a clock",
        "a cup",
        "a chair",
        "a table",
        "a doll",
        "a toy",
        "a figurine",
        "a dollhouse interior",
        "a miniature house",
    ],
    "memes": [
        "a funny image",
        "an internet meme",
        "a reaction image",
        "a humorous picture",
        "a viral photo",
        "a relatable content image",
        "a sarcastic image",
        "a comedic picture with text",
        "a meme with text overlay",
        "a picture with impact font",
        "a popular internet joke visual",
        "a satirical image",
        "a captioned image",
        "a funny drawing",
        "a web comic",
    ],
    "pets": [
        "a dog",
        "a cat",
        "a bird",
        "a fish",
        "a pet animal",
        "a domestic animal",
        "a puppy",
        "a kitten",
        "a loyal companion",
        "an animal portrait",
        "a pet playing",
        "a cat sleeping",
        "a dog running",
        "a furry friend",
        "a household pet",
        "a cute animal",
        "a feline",
        "a canine",
        "a pet indoors",
        "an animal looking at the camera",
        "a pet on a chair",
        "a cat on furniture",
        "a relaxing pet",
        "a happy animal",
        "a domestic animal in a home setting",
        "a companion animal",
        "a pet in a living room",
        "a pet on a sofa",
        "a cat lounging",
        "an indoor pet",
    ],
    "food": [
        "food",
        "a meal",
        "a dish",
        "a dessert",
        "a fruit",
        "a vegetable",
        "a drink",
        "a beverage",
        "a culinary creation",
        "a restaurant meal",
        "home cooking",
        "a healthy meal",
        "junk food",
        "a snack",
        "a refreshing drink",
    ],
    "nature": [
        "a landscape",
        "a mountain",
        "a forest",
        "a river",
        "a lake",
        "an ocean",
        "a beach",
        "flowers",
        "trees",
        "a sunset",
        "a sunrise",
        "a natural scene",
        "wildlife",
        "a garden",
        "a desert",
        "a sky",
        "clouds",
        "a natural phenomenon",
    ],
    "vehicles": [
        "a car",
        "a truck",
        "a motorcycle",
        "an airplane",
        "a boat",
        "a bicycle",
        "a mode of transport",
        "a train",
        "a bus",
        "a commercial vehicle",
        "a sports car",
        "a passenger car",
        "a cargo truck",
        "a plane taking off",
        "a ship",
        "a motorbike",
        "a scooter",
        "a public transport vehicle",
    ],
    "travel": [
        "a travel destination",
        "a landmark",
        "a vacation spot",
        "a tourist attraction",
        "a foreign city",
        "a road trip scene",
        "an airport terminal",
        "a suitcase",
        "a passport",
        "a map",
        "a famous place",
        "a holiday location",
        "a cultural site",
        "a tourist destination",
        "a historical site",
        "a place of worship",
    ],
    "art_and_culture": [
        "a painting in a gallery",
        "a sculpture in a museum",
        "a classical drawing",
        "a museum exhibit on display",
        "a performance art show",
        "a cultural artifact",
        "a traditional craft display",
        "a music instrument being played on stage",
        "a theatrical play",
        "a live concert",
        "an art gallery opening",
        "street art mural",
        "a historical monument",
        "an ancient ruin site",
        "a ceremonial object in a cultural context",
        "a cultural festival event with traditions",
        "fine art exhibition",
        "a masterpiece artwork",
        "a historical artifact",
    ],
    "uncategorized": ["something unidentifiable", "miscellaneous", "other"],
}

# Priority keywords for direct or boosted categorization, often implying high confidence.
# These will be checked first using string matching in captions/OCR.
PRIORITY_KEYWORDS = {
    "architecture": [
        "a monument",
        "historical architecture",
        "modern architecture",
        "a temple",
        "a church",
        "a mosque",
        "a cathedral",
        "a pagoda",
        "a palace",
        "a castle",
        "a shrine",
    ],
    "people": [
        "selfie",
        "portrait",
        "group photo",
        "family photo",
        "friends",
        "person",
        "people",
        "man",
        "woman",
        "child",
        "adult",
        "face",
        "faces",
        "human",
        "humans",
        "mustache",
        "beard",
        "smile",
        "smiling",
        "group",
        "crowd",
        "gathering",
    ],
    "sightseeing": [
        "tourist attraction",
        "sightseeing",
        "landmark",
        "guided tour",
        "tourists",
        "arch",
        "tower",
        "beach",
        "park",
        "bench",
        "building",
        "monument",
        "shrine",
    ],
    "documents": [
        "invoice",
        "receipt",
        "contract",
        "certificate",
        "diploma",
        "form",
        "letter",
        "report",
        "scanned document",
    ],
    "achievements": [
        "trophy",
        "award",
        "medal",
        "champion",
        "certificate",
        "diploma",
        "recognition",
        "graduation",
        "achievement",
        "winner",
        "victory",
        "accomplishment",
        "honor",
        "prize",
    ],
    "memes": [
        "meme",
        "funny",
        "lol",
        "hilarious",
        "reaction",
        "template",
        "viral",
        "joke",
        "relatable",
        "sarcastic",
        "comic",
        "webcomic",
    ],
    "pets": [
        "dog",
        "cat",
        "puppy",
        "kitten",
        "pet",
        "animal",
        "furry friend",
        "feline",
        "canine",
    ],
    "food": [
        "food",
        "meal",
        "dish",
        "recipe",
        "delicious",
        "eating",
        "cuisine",
        "dessert",
        "drink",
    ],
    "vehicles": [
        "car",
        "truck",
        "bike",
        "plane",
        "boat",
        "train",
        "bus",
        "driving",
        "automobile",
    ],
    "travel": [
        "travel",
        "vacation",
        "trip",
        "landmark",
        "tourist",
        "destination",
        "explore",
        "journey",
    ],
    "nature": [
        "nature",
        "forest",
        "mountain",
        "river",
        "lake",
        "ocean",
        "beach",
        "flower",
        "tree",
        "landscape",
        "sunset",
    ],
}

# Specific indicators for memes, used for a more robust meme detection heuristic.
# Using a set for faster lookup.
MEME_INDICATOR_SET = {
    "when you",
    "tfw",
    "mfw",
    "me when",
    "my face when",
    "that moment when",
    "nobody:",
    "everyone:",
    "pov",
    "brb",
    "irl",
    "this is fine",
    "distracted boyfriend",
    "success kid",
    "drake hotline bling",
    "one does not simply",
    "expand dong",
    "doge",
    "pepe the frog",
    "grumpy cat",
    "blinking white guy",
    "surprised pikachu",
    "woman yelling at cat",
    "ancient aliens guy",
    "boardroom meeting suggestion",
    "change my mind",
    "is this a pigeon",
    "arthur's fist",
    "stonks",
    "big brain time",
    "galaxy brain",
    "epic handshake",
    "mocking spongebob",
    "crying jordan",
    "confused math lady",
    "bad luck brian",
    "first world problems",
    "good guy greg",
    "scumbag steve",
    "ermagerd",
    "all the things",
    "y u no",
    "too damn high",
    "x all the y",
    "am i the only one",
    "what if i told you",
    "i miss the engrish",
    "challenge accepted",
    "x, x everywhere",
    "not sure if",
    "you're gonna have a bad time",
    "doggo",
    "floof",
    "chonk",
    "swole doge",
    "cheems",
    "cringe",
    "how to",
    "nice",
    "frog",
}
